### ISSUE TITLE
border-radiusの-moz-prefixは必要無いと思われます

### ISSUE THREAD

**Issue by kubosho** [sanographix/sanographix.github.com#8]
https://github.com/sanographix/sanographix.github.com/blob/master/public/tumblr/tokusetsu2/css/_mixin.less#L68-L71

で定義されている、border-radiusの-moz-prefixですが http://caniuse.com/#feat=border-radius によると、Firefox 4からはborder-radiusに-moz-prefixがいらなくなっています。

また、[旧バージョンの Firefox 3.6 と Thunderbird 3.1 はサポートが終了しました - まだお使いの方は早急に更新を | Mozilla Japan ブログ](http://www.mozilla.jp/blog/entry/9135/)によると、2012/04/23にFirefox 3.6のサポートは終了しているので、もはや-moz-prefixは必要ないと思われます。

**Comment by kubosho** [comment]
一応、手元で直したものはあるのですが、他にも同じようなmixinが定義されている箇所があり、どこを修正したら良いのか分からなくなってしまったのでissueを立てました。

https://github.com/kubosho/sanographix.github.com/commit/ec59676f5b3ee3a0fb54549a735dff48774b0e81

**Comment by sanographix** [comment]
@kubosho なるほど、そうだったんですね。
このリポジトリ、自分用のファイルが雑多に入っているんですが、ひとまず `/public/tumblr/` 以下の  mixin を修正しようと思います。
ご報告ありがとうございました。

**Comment by kubosho** [comment]
`/public/tumblr/` 以下の mixin を修正する件、了解です。
